# Generated by Django 5.2.5 on 2025-08-29 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_rename_views_count_film_total_views_and_more'),
        ('subscription', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='film',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.film'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['film'], name='subscriptio_film_id_a15975_idx'),
        ),
    ]
