# Generated by Django 5.2.5 on 2025-08-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planfeatureassignment',
            name='limit_value',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='limit_value',
            field=models.PositiveIntegerField(blank=True, help_text='Set a numeric limit. Leave empty or 0 for unlimited.', null=True),
        ),
    ]
