# Generated by Django 5.2.5 on 2025-08-26 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='paypal_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
