# Generated by Django 5.2.5 on 2025-08-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_usersubscription_paypal_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
