# Generated by Django 5.2.5 on 2025-08-22 10:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_remove_planfeatureassignment_limit_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriptionusage',
            unique_together={('user', 'subscription')},
        ),
        migrations.RemoveField(
            model_name='subscriptionusage',
            name='feature',
        ),
    ]
