# Generated by Django 5.2.5 on 2025-08-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_alter_usersubscription_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='paypal_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
