# Generated by Django 5.2.5 on 2025-08-22 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_alter_subscriptionusage_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionusage',
            old_name='free_used_value',
            new_name='ai_used_value',
        ),
        migrations.RenameField(
            model_name='subscriptionusage',
            old_name='used_value',
            new_name='free_ai_used_value',
        ),
    ]
