"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import os
from dotenv import load_dotenv
# Load environment variables from .env file
load_dotenv()

# for cloudinary
import cloudinary
import cloudinary.uploader
import cloudinary.api

# cloudinary.config( 
#   cloud_name = "dubsxif8w",
#   api_key = "344857482292291",
#   api_secret = "w_HqV196OdrQZYs7LGzQUFFOsBc",
#   secure = True
# )

cloudinary.config( 
  cloud_name = "dvyff8deo",
  api_key = "648848566517129",
  api_secret = "U1xOQXN7MEJGJBKktKw73-Z9sGg",
  secure = True
)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%6qh_!ymgc!2g%qju&67d2+p6!aqo-ur!5a$s3_(iyau5jq&*-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'equal-evidently-terrier.ngrok-free.app']



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps or libraries
    'rest_framework',
    'rest_framework_simplejwt',

    # For Upload cloudinary
    'cloudinary',
    'cloudinary_storage',

    # Custom apps
    'accounts',
    'movie',
    'subscription',
    'reelbux',
    'distro',
]

# CustomUser Model
AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # Directory for custom templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'

# MEDIA_URL = '/media/'

# STATICFILES_DIRS = [BASE_DIR / 'static']
# STATIC_ROOT = BASE_DIR / 'assets'
# MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

# JWT settings
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=10),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=50),
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),   # <-- FIXED
}


# Email settings
EMAIL_USE_SSL = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'munjuralom.jvai@gmail.com'
EMAIL_HOST_PASSWORD = 'tlyoselspygammzz'
EMAIL_PORT = 465
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'


CSRF_TRUSTED_ORIGINS = ['https://equal-evidently-terrier.ngrok-free.app']


#---------
# Cloudinary credentials
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'dvyff8deo',
    'API_KEY': '648848566517129',
    'API_SECRET': 'U1xOQXN7MEJGJBKktKw73-Z9sGg',
}

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'


#Stripe Payment Price id define
STRIPE_PRICE_BASIC = os.getenv("STRIPE_PRICE_BASIC")
STRIPE_PRICE_PRO = os.getenv("STRIPE_PRICE_PRO")
STRIPE_PRICE_ELITE = os.getenv("STRIPE_PRICE_ELITE")

# Stripe keys
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")
STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET")


#PayPal
# PAYPAL_TEST = True
# PAYPAL_RECEIVER_EMAIL = 'sb-u47h43j45194681@business.example.com' # where cash is paid into
PAYPAL_CLIENT_ID = "ASz00DmJkxuQ75fQEuifFOdsCQth58evy6G82OqMuvXq8IEysYI28wWftFKDzx0htpRuBTttnl3K8Ynk"
PAYPAL_CLIENT_SECRET = "EK3qr2n7kBdljYjLaVVNNKcHxzpu8S9sX0lkh4eYLtWUSf30cN04gkkv3DTi_waqyw3-5TKhBlW8xJZs"


# CSRF_TRUSTED_ORIGINS = [
#     'https://equal-evidently-terrier.ngrok-free.app',
# ]