# Generated by Django 5.2.5 on 2025-08-15 03:00

import cloudinary.models
import django.db.models.deletion
import movie.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.CharField(default=movie.models.generate_short_uuid, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('logline', models.CharField(blank=True, max_length=280)),
                ('film_type', models.CharField(choices=[('movie', 'Movie'), ('drama', 'Drama'), ('short', 'Short'), ('documentary', 'Documentary'), ('series', 'Series')], max_length=20)),
                ('thumbnail', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('trailer', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('trailer_hls_url', models.URLField(blank=True)),
                ('trailer_duration_s', models.PositiveIntegerField(default=0)),
                ('full_film', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('film_hls_url', models.URLField(blank=True)),
                ('film_duration_s', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('review', 'In Review'), ('published', 'Published'), ('rejected', 'Rejected')], default='review', max_length=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('rent_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rental_hours', models.PositiveIntegerField(default=48)),
                ('buy_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('total_earning', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('filmmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='films', to=settings.AUTH_USER_MODEL)),
                ('genre', models.ManyToManyField(blank=True, to='movie.genre')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
