# Generated by Django 5.2.5 on 2025-09-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmview',
            name='carrent_watch_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
