# Generated by Django 5.2.5 on 2025-08-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='full_film_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='trailer_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
