# Generated by Django 5.2.5 on 2025-08-30 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFilms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('Buy', 'Lifetime'), ('Rent', 'Temporary')], max_length=10)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_film_access', to='movie.film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_films', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'My Film',
                'verbose_name_plural': 'My Films',
                'unique_together': {('user', 'film', 'access_type')},
            },
        ),
        migrations.DeleteModel(
            name='FilmAccess',
        ),
    ]
