# Generated by Django 5.2.5 on 2025-08-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='views_count',
            new_name='total_views',
        ),
        migrations.AddField(
            model_name='film',
            name='unique_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
