# Generated by Django 5.2.5 on 2025-08-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='status',
            field=models.CharField(choices=[('REVIEW', 'Under Review'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected')], default='REVIEW', max_length=12),
        ),
    ]
