# Generated by Django 5.2.5 on 2025-09-06 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_filmview_carrent_watch_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmview',
            old_name='carrent_watch_time',
            new_name='current_watch_time',
        ),
    ]
