# Generated by Django 5.2.5 on 2025-08-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_rename_views_count_film_total_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmview',
            name='watched_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
