# Generated by Django 5.2.5 on 2025-08-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_film_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='film_type',
            field=models.CharField(choices=[('MOVIE', 'Movie'), ('DRAMA', 'Drama'), ('SHORT', 'Short Film'), ('DOCUMENTARY', 'Documentary'), ('SERIES', 'Series')], max_length=20),
        ),
    ]
