# Generated by Django 5.2.5 on 2025-08-20 03:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_rename_views_film_views_count_filmview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmview',
            old_name='user',
            new_name='viewer',
        ),
        migrations.AlterUniqueTogether(
            name='filmview',
            unique_together={('film', 'viewer')},
        ),
    ]
