# Generated by Django 5.2.5 on 2025-09-06 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_rename_carrent_watch_time_filmview_current_watch_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myfilms',
            options={'ordering': ['-start_date'], 'verbose_name': 'My Film', 'verbose_name_plural': 'My Films'},
        ),
        migrations.AlterUniqueTogether(
            name='myfilms',
            unique_together=set(),
        ),
    ]
