# Generated by Django 5.2.5 on 2025-08-21 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_film_film_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('Buy', 'Buy'), ('Rent', 'Rent')], max_length=10)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='movie.film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Film Access',
                'verbose_name_plural': 'Film Accesses',
                'unique_together': {('user', 'film', 'access_type')},
            },
        ),
    ]
