# Generated by Django 5.2.5 on 2025-09-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_myfilms_options_alter_myfilms_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='thumbnail_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
