# Generated by Django 5.2.5 on 2025-08-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_filmaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmaccess',
            name='access_type',
            field=models.CharField(choices=[('Buy', 'Lifetime'), ('Rent', 'Temporary')], max_length=10),
        ),
    ]
